# Generated by Django 4.1.3 on 2022-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('instock', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Allproduct',
        ),
    ]
